<?php 
define('CONSOLIDATED_BILLING_INSTRUCTION_VERSION', '1.0');
define('CONSOLIDATED_BILLING_INSTRUCTION_FOLDER', 'consolidated_billing_instruction');
define('CONSOLIDATED_BILLING_INSTRUCTION_PATH', MODULES_PATH.CONSOLIDATED_BILLING_INSTRUCTION_FOLDER.'/');
